export const FETCH_PROPERTIES = "FETCH_PROPERTIES"
export const FETCH_PROPERTY = "FETCH_PROPERTY"
export const UPDATE_PROPERTY = "UPDATE_PROPERTY"
export const CREATE_PROPERTY = "CREATE_PROPERTY"
export const DESTROY_PROPERTY = "DESTROY_PROPERTY"

export const FETCH_PROPERTY_ICALS = "FETCH_PROPERTY_ICALS"
export const FETCH_PROPERTY_ICAL = "FETCH_PROPERTY_ICAL"
export const UPDATE_PROPERTY_ICAL = "UPDATE_PROPERTY_ICAL"
export const CREATE_PROPERTY_ICAL = "CREATE_PROPERTY_ICAL"
export const DESTROY_PROPERTY_ICAL = "DESTROY_PROPERTY_ICAL"

export const FETCH_PROPERTY_RESERVATIONS = "FETCH_PROPERTY_RESERVATIONS"
export const FETCH_RESERVATION = "FETCH_RESERVATION"

export const ASSIGN_CLEANER_TO_RESERVATION = "ASSIGN_CLEANER_TO_RESERVATION"
export const REMOVE_CLEANER_FROM_RESERVATION = "REMOVE_CLEANER_FROM_RESERVATION"

export const SIGN_IN = "SIGN_IN"
export const SIGN_IN_LOCAL_STORAGE = "SIGN_IN_LOCAL_STORAGE"
export const SAVE_USER_SESSION = "SAVE_USER_SESSION"
export const SIGN_OUT = "SIGN_OUT"

export const FETCH_USERS = "FETCH_USERS"
export const FETCH_USER = "FETCH_USER"
export const UPDATE_USER = "UPDATE_USER"
export const CREATE_USER = "CREATE_USER"
export const DESTROY_USER = "DESTROY_USER"

export const TOGGLE_RESERVATIONS = "TOGGLE_RESERVATIONS"
export const TOGGLE_CLEANINGS = "TOGGLE_CLEANINGS"