export const FETCH_PROPERTIES = "FETCH_PROPERTIES"
export const FETCH_PROPERTY_RESERVATIONS = "FETCH_PROPERTY_RESERVATIONS"

export const ASSIGN_CLEANER_TO_RESERVATION = "ASSIGN_CLEANER_TO_RESERVATION"
export const REMOVE_CLEANER_FROM_RESERVATION = "REMOVE_CLEANER_FROM_RESERVATION"

export const SIGN_IN = "SIGN_IN"
export const SIGN_OUT = "SIGN_OUT"