export const FETCH_PROPERTIES = "FETCH_PROPERTIES"
export const FETCH_PROPERTY_RESERVATIONS = "FETCH_PROPERTY_RESERVATIONS"
export const FETCH_RESERVATION = "FETCH_RESERVATION"

export const ASSIGN_CLEANER_TO_RESERVATION = "ASSIGN_CLEANER_TO_RESERVATION"
export const REMOVE_CLEANER_FROM_RESERVATION = "REMOVE_CLEANER_FROM_RESERVATION"

export const SIGN_IN = "SIGN_IN"
export const SIGN_OUT = "SIGN_OUT"

export const FETCH_USERS = "FETCH_USERS"
export const FETCH_USER = "FETCH_USER"